# Generated by Django 2.0.5 on 2018-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-sent_date',)},
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.TextField(default='Conversation', max_length=40),
        ),
    ]
