# Generated by Django 2.0.5 on 2018-05-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180527_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='members',
        ),
    ]
