# Generated by Django 2.0.5 on 2018-05-27 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_remove_conversation_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='Conversation', max_length=40),
        ),
    ]
